configuration: Release

image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "3.3.0-ci.$($env:APPVEYOR_BUILD_NUMBER)+sha.$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

cache:
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'

before_build:
  - dotnet restore --verbosity quiet
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory packages -Verbosity quiet
  - nuget install Codecov -Version 1.0.4 -OutputDirectory packages -Verbosity quiet

build:
  project: Ninject.Extensions.ChildKernel.sln
  verbosity: quiet
  
test_script:
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -oldstyle -returntargetcode -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --configuration Release --no-build src\Ninject.Extensions.ChildKernel.Test" -filter:"+[Ninject.Extensions.ChildKernel]*" -excludebyattribute:*.ExcludeFromCodeCoverage*;*.Obsolete* -output:".\Ninject.Extensions.ChildKernel_coverage.xml"
  - packages\Codecov.1.0.4\tools\codecov.exe -f "C:\projects\ninject-extensions-childkernel\Ninject.Extensions.ChildKernel_coverage.xml"

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: Sn05A/FiUAlID5v31uaf5EZuYCSo4frLONtrCY+cwY265dU2JUZsl2+sjVeLQyz/
  on:
    appveyor_repo_tag: true
